/**
 * Fiktive Namenspools (Konzept Abschnitt 5).
 * Bewusst erfunden, damit keine echten Vereine oder Personen verwendet werden.
 */

export interface NamePool {
  firstNames: string[];
  lastNames: string[];
  cities: string[];
  clubPrefixes: string[];
  clubSuffixes: string[];
  managerFirst: string[];
}

export const NAME_POOLS: Record<string, NamePool> = {
  falkenland: {
    firstNames: [
      'Jonas', 'Nico', 'Lennard', 'Fabian', 'Tobias', 'Marek', 'Silas', 'Kilian',
      'Arne', 'Ruben', 'Malte', 'Jannis', 'Till', 'Bennet', 'Hendrik', 'Levin',
      'Moritz', 'Anton', 'Ole', 'Elias', 'Emil', 'Fynn', 'Joris', 'Marlon',
      'Nils', 'Piet', 'Quirin', 'Sven', 'Thore', 'Valentin', 'Aaron', 'Bastian',
      'Cedric', 'Damian', 'Erik', 'Florian', 'Gero', 'Hauke', 'Ilja', 'Jakob',
      'Konrad', 'Lasse', 'Mattis', 'Norik', 'Oskar', 'Paul', 'Rasmus', 'Simon',
      'Adrian', 'Bjarne', 'Carlo', 'Dennis', 'Eike', 'Falk',
      'Gunnar', 'Henrik', 'Ingo', 'Jost', 'Kai', 'Leif',
      'Merlin', 'Nikolas', 'Ove', 'Philemon', 'Ragnar', 'Sebastian',
      'Timo', 'Uwe', 'Veit', 'Wilko', 'Yannik', 'Arved',
      'Bosse', 'Claas', 'Detlev', 'Enno', 'Frerk', 'Gustav',
    ],
    lastNames: [
      'Ahrenberg', 'Brenneke', 'Dornbusch', 'Eichhorst', 'Fischbach', 'Grunewald',
      'Habicht', 'Immhoff', 'Jansen', 'Kaltenbach', 'Lehnhardt', 'Moorbach',
      'Neuhaus', 'Ostermann', 'Pfeilstein', 'Quandt', 'Reitmeier', 'Sturmberg',
      'Tannhoff', 'Uhlig', 'Vetterlein', 'Waldschmidt', 'Zeidler', 'Bergmann',
      'Krauss', 'Wendland', 'Osterloh', 'Nordmann', 'Reichl', 'Schönfeld',
      'Falkner', 'Hartmann', 'Steinbach', 'Wieland', 'Reinhardt', 'Kohlmann',
      'Baumgart', 'Lindner', 'Grothe', 'Vogelsang', 'Ebert', 'Sandberg',
      'Kastner', 'Meinhardt', 'Rothbauer', 'Wintersen', 'Dürrhoff', 'Espenlaub',
      'Gerlach', 'Holtmann', 'Isenbeck', 'Kerner', 'Lauterbach', 'Mühlberg',
      'Nagelschmidt', 'Oberweis', 'Petersen', 'Rammelsberg', 'Seewald', 'Trautner',
      'Amsel', 'Birkholz', 'Cordes', 'Drewes', 'Eggersglues', 'Falkenrath',
      'Hövelmann', 'Isernhagen', 'Jaspers', 'Kienbaum', 'Lohmeyer', 'Marquardt',
      'Niebuhr', 'Oldenburg', 'Pflüger', 'Quirin', 'Rothaug', 'Siebenhaar',
      'Trittau', 'Ummen', 'Voigtländer', 'Wattenscheid', 'Zieseniss', 'Ahlgrimm',
      'Brockhaus', 'Dünnebier', 'Ellerbrock', 'Fassbender', 'Grothues', 'Hillebrand',
      'Kettenbach', 'Lütkemeyer', 'Mohrbach', 'Nienkämper', 'Pralle', 'Reddemann',
      'Südkamp', 'Thelen', 'Wolterding',
      // Ein paar schrullige darunter - selten genug, dass sie auffallen.
      'Zwiebelmann', 'Federleicht', 'Sonntagskind', 'Klingelhöfer',
      'Nebelschick', 'Wunderlich', 'Sausewind', 'Krautgartner',
      'Morgenroth', 'Pusteblume', 'Donnerhack', 'Kuchenbecker',
    ],
    cities: [
      'Nordheim', 'Adlerstadt', 'Rotenburg', 'Bergwald', 'Falkensee', 'Steinfurt',
      'Hohental', 'Weissbrunn', 'Eichenau', 'Sturmberg', 'Moorbach', 'Lindental',
      'Kaltenau', 'Grauenfels', 'Tannbruck', 'Silberbach', 'Wolfstein', 'Ravensfeld',
      'Ellerbach', 'Hafenau', 'Dornstadt', 'Kranichberg', 'Marbeck', 'Ossenfurt',
      'Pirkheim', 'Quellenau', 'Rehbrunn', 'Sonnenfels', 'Tiefental', 'Ulrichshain',
      'Vogelsbach', 'Wehrhagen', 'Zellerbrunn', 'Ammersfeld', 'Blankenau', 'Cranzberg',
      'Dürnstein', 'Erlenkamp', 'Freiberg', 'Grimmental', 'Hollerbach', 'Innau',
      'Jagsthausen', 'Klingenau', 'Lauterfeld', 'Mühlenstadt', 'Neuwiese', 'Oberrain',
      'Perlbach', 'Rauental', 'Schwarzenau', 'Talheim', 'Uttenhain', 'Vierbrunn',
      'Wildbach', 'Zwieselau', 'Aschenfeld', 'Bruckstadt', 'Cornau', 'Dahlenberg',
    ],
    clubPrefixes: ['FC', 'SV', 'SC', 'VfB', 'TSV', 'VfL', 'SpVgg', 'FSV', 'BSC', 'TuS', '1. FC', 'SG'],
    clubSuffixes: ['', '', '', '', '08', '04', '1911', '96', 'United'],
    managerFirst: ['Gunnar', 'Detlev', 'Reiner', 'Ulf', 'Wolfram', 'Heiko', 'Bernd', 'Klaas'],
  },

  albion: {
    firstNames: [
      'Callum', 'Reece', 'Nathan', 'Owen', 'Declan', 'Jaden', 'Marcus', 'Harvey',
      'Corey', 'Elliot', 'Finley', 'Grayson', 'Hugo', 'Isaac', 'Jarrod', 'Kyle',
      'Liam', 'Mason', 'Noah', 'Oscar', 'Preston', 'Quinn', 'Rory', 'Spencer',
      'Toby', 'Vince', 'Wesley', 'Zach', 'Adam', 'Brandon', 'Cody', 'Dexter',
      'Alfie', 'Bradley', 'Gareth', 'Jamie', 'Kieran', 'Lewis',
      'Vincent', 'Zachary', 'Archie', 'Bailey', 'Casey', 'Dominic',
      'Edward', 'Frankie', 'Grant', 'Hugh', 'Ivor', 'Jude',
      'Kai', 'Louie', 'Miles', 'Noel', 'Ollie',
    ],
    lastNames: [
      'Ashcombe', 'Barrowman', 'Cranfield', 'Denholm', 'Ellery', 'Fairbourne',
      'Grimshaw', 'Hollingworth', 'Ingram', 'Jessop', 'Kendrick', 'Lockhart',
      'Marchmont', 'Northcote', 'Oakley', 'Prescott', 'Quiller', 'Radcliffe',
      'Stanmore', 'Thackeray', 'Underhill', 'Vanbrough', 'Whitlock', 'Yardley',
      'Beckworth', 'Carrington', 'Dunmore', 'Everleigh', 'Fenwick', 'Halloway',
      'Ackroyd', 'Barlowe', 'Eastwick', 'Fairbrass', 'Ingleby', 'Jardine',
      'Kenworthy', 'Loxley', 'Marchbank', 'Netherwood', 'Ormerod', 'Pemberley',
      'Quarrier', 'Ravensworth', 'Stanbury', 'Thirlwall', 'Vosper', 'Whitcombe',
      'Ashfield', 'Brackenbury', 'Culverhouse', 'Denby', 'Ellingham', 'Fothergill',
      'Garrowby', 'Hawksworth', 'Illingworth', 'Kettlewell', 'Lampeter', 'Mowbray',
      'Norbury', 'Pickersgill', 'Rusholme', 'Swaithe', 'Tarleton', 'Wexford',
      'Yeardley', 'Bramhall', 'Crossley', 'Dearnley', 'Gaunt', 'Holbeck',
      'Kirkbride', 'Linthwaite', 'Middlebrook', 'Osgathorpe', 'Prestwich', 'Rowntree',
      'Sedgwick', 'Threlfall', 'Wolstenholme', 'Yeadon', 'Balderstone',
      // Ein paar schrullige darunter - selten genug, dass sie auffallen.
      'Widdicombe', 'Bumblethorpe', 'Pennyfeather', 'Quickfall',
      'Ramsbottom', 'Sillitoe', 'Twizzle', 'Wagstaff',
      'Bagshaw', 'Clutterbuck', 'Drinkwater', 'Fiddleton',
    ],
    cities: [
      'Kingsmoor', 'Ashford', 'Northbridge', 'Redcliff', 'Whitmore', 'Ironvale',
      'Harborne', 'Blackwell', 'Stonebury', 'Eastgate', 'Grimsby Vale', 'Loxbridge',
      'Westhaven', 'Thornwick', 'Colbourne', 'Marsden', 'Pendleton', 'Ravenshaw',
    ],
    clubPrefixes: ['', '', '', '', 'FC'],
    clubSuffixes: ['United', 'City', 'Rovers', 'Town', 'Athletic', 'Wanderers', 'Albion', 'County', 'FC', 'Forest'],
    managerFirst: ['Neville', 'Roy', 'Graham', 'Terry', 'Alan', 'Duncan'],
  },

  iberia: {
    firstNames: [
      'Alvaro', 'Bruno', 'Cesar', 'Diego', 'Enzo', 'Fermin', 'Gonzalo', 'Hector',
      'Ivan', 'Joaquin', 'Lucas', 'Mateo', 'Nacho', 'Oriol', 'Pablo', 'Quim',
      'Rafa', 'Sergio', 'Tomas', 'Unai', 'Vicente', 'Xabi', 'Yago', 'Adrian',
      'Borja', 'Carlos', 'Dani', 'Emilio', 'Fabio', 'Guillem',
      'Cristobal', 'Fernando', 'Ignacio', 'Manuel', 'Nicolas', 'Oscar',
      'Rodrigo', 'Xavier', 'Dario', 'Eduardo', 'Felipe', 'Gabriel',
      'Hugo', 'Ismael', 'Javier', 'Leandro', 'Marcos', 'Nuno',
      'Octavio', 'Ruben', 'Salvador', 'Teodoro', 'Ulises', 'Vasco',
    ],
    lastNames: [
      'Almendral', 'Bermejo', 'Carrascal', 'Delgadillo', 'Escrivan', 'Fuentesol',
      'Garzon', 'Herrejon', 'Iriarte', 'Jarama', 'Lozano', 'Miravalles',
      'Narvaez', 'Olmedilla', 'Peralta', 'Quiroga', 'Requena', 'Salcedo',
      'Tordesillo', 'Urrutia', 'Valcarce', 'Ybarra', 'Zamorano', 'Bellido',
      'Cifuentes', 'Duran', 'Endrino', 'Ferreiro', 'Galvan', 'Hinojosa',
      'Abascal', 'Carranza', 'Escalante', 'Fontanals', 'Guijarro', 'Higueras',
      'Izaguirre', 'Jaramillo', 'Lastra', 'Madrazo', 'Nogueira', 'Olivares',
      'Pardal', 'Redondela', 'Tarazona', 'Ubierna', 'Valdivielso', 'Zubiria',
      'Alcantara', 'Benavides', 'Casanueva', 'Domingues', 'Estevez', 'Frontela',
      'Gorostiza', 'Herrezuelo', 'Larrazabal', 'Mendizabal', 'Narbona', 'Ochandiano',
      'Peralejo', 'Quintanar', 'Requejo', 'Sotomayor', 'Trapero', 'Uriondo',
      'Villaverde', 'Zaldivar', 'Amezaga', 'Bustinza', 'Corcuera', 'Elorriaga',
      'Garaikoetxea', 'Landaluce', 'Olabarria', 'Pagoaga', 'Retegui', 'Sarasola',
      'Txurruka', 'Zabaleta', 'Barrenetxea', 'Etxeberria',
      // Ein paar schrullige darunter - selten genug, dass sie auffallen.
      'Cascabel', 'Malapata', 'Pimentel', 'Rebolledo',
      'Tortolero', 'Vinagre', 'Caramelo', 'Zapatero',
      'Buenaventura', 'Cascarilla', 'Peluchez', 'Tarambana',
    ],
    cities: [
      'Valmera', 'Castilbao', 'Riosanto', 'Montverde', 'Puertola', 'Alcazara',
      'Sierrablanca', 'Navalcruz', 'Torrenova', 'Ribadelmar', 'Espinar', 'Lagunilla',
    ],
    clubPrefixes: ['CD', 'CF', 'SD', 'UD', 'Atletico', 'Sporting', 'Deportivo', 'Real'],
    clubSuffixes: ['', '', '', 'FC'],
    managerFirst: ['Ramon', 'Julen', 'Paco', 'Ernesto', 'Luis'],
  },

  calcio: {
    firstNames: [
      'Alessio', 'Bruno', 'Cristian', 'Davide', 'Emanuele', 'Fabrizio', 'Gianluca',
      'Ivano', 'Lorenzo', 'Matteo', 'Nicolo', 'Ottavio', 'Pietro', 'Riccardo',
      'Simone', 'Tommaso', 'Umberto', 'Valerio', 'Andrea', 'Federico', 'Giacomo',
      'Leonardo', 'Marco', 'Stefano',
      'Alberto', 'Bernardo', 'Cesare', 'Dario', 'Enrico', 'Filippo',
      'Giorgio', 'Ignazio', 'Luca', 'Massimo', 'Nicola', 'Orlando',
      'Paolo', 'Raffaele', 'Salvatore', 'Tiziano', 'Ubaldo', 'Vittorio',
      'Antonio', 'Domenico', 'Elia', 'Fausto', 'Gabriele', 'Ilario',
      'Lodovico', 'Michele', 'Nunzio', 'Oreste', 'Pasquale', 'Renzo',
      'Sergio', 'Teodoro', 'Vincenzo', 'Amedeo', 'Bartolomeo', 'Carmine',
      'Dante', 'Ettore', 'Flavio', 'Giulio', 'Lamberto', 'Mauro',
      'Nino', 'Ottone', 'Pierluigi', 'Rocco',
    ],
    lastNames: [
      'Baldracchi', 'Corvetti', 'Danesi', 'Ferrandino', 'Grimaldelli', 'Iacovone',
      'Lombardelli', 'Mazzanti', 'Nardone', 'Orsolini', 'Perrotta', 'Quaranta',
      'Rovelli', 'Scarpone', 'Tornatore', 'Ubaldini', 'Vercelli', 'Zaccagni',
      'Bellotti', 'Caruso', 'Dellavalle', 'Esposti', 'Fiorillo', 'Gattuzzo',
      'Amoruso', 'Bertolazzi', 'Cannavaro', 'Diamanti', 'Evangelisti', 'Fioravanti',
      'Guccione', 'Imbriani', 'Lanzafame', 'Montervino', 'Nocerino', 'Occhipinti',
      'Pandolfini', 'Quagliarulo', 'Ravanelli', 'Sabatini', 'Tavecchio', 'Ubertini',
      'Valentini', 'Zamparini', 'Battistoni', 'Cerruti', 'Donadoni', 'Empoli',
      'Ferrarese', 'Giannotti', 'Iachini', 'Lucarelli', 'Malagoli', 'Nicolosi',
      'Ottaviani', 'Petrucci', 'Rambaudi', 'Sartori', 'Tremonti', 'Vanoli',
      'Zampini', 'Bagnoli', 'Calzoni', 'Dossena', 'Fabbrini', 'Ghirardi',
      'Loparco', 'Marchetti', 'Nastasi', 'Pizzaballa', 'Riolfo', 'Sgarbossa',
      'Toldini', 'Vialli', 'Zenoni', 'Arcuri', 'Brunelli', 'Cordoba',
      'Dellacasa', 'Fanucci', 'Guidolin', 'Lupatelli', 'Moriero', 'Paganini',
      'Ruggiero', 'Serena', 'Tacchinardi', 'Vergassola', 'Zauri', 'Bonaventura',
      // Ein paar schrullige darunter - selten genug, dass sie auffallen.
      'Frittella', 'Papavero', 'Scarpetta', 'Trombetta',
      'Zuccherini', 'Mozzarelli', 'Confetti', 'Rondinella',
      'Spaghetto', 'Verdolino', 'Tacchetti', 'Girandola',
    ],
    cities: [
      'Montaldo', 'Verrano', 'Portosano', 'Castelmare', 'Lucanera', 'Aventino',
      'Ronciglio', 'Salvatera', 'Belforte', 'Cimalta', 'Doriano', 'Fossanuova',
    ],
    clubPrefixes: ['AC', 'US', 'FC', 'Calcio', 'AS', 'SS'],
    clubSuffixes: ['', '', '', '1909', 'Calcio'],
    managerFirst: ['Massimo', 'Claudio', 'Gianpiero', 'Sandro', 'Fulvio'],
  },

  gallia: {
    firstNames: [
      'Antoine', 'Baptiste', 'Cedric', 'Dimitri', 'Etienne', 'Florian', 'Guillaume',
      'Hugo', 'Julien', 'Kevin', 'Ludovic', 'Mathis', 'Noel', 'Olivier', 'Pierre',
      'Quentin', 'Remy', 'Sebastien', 'Thibault', 'Ulysse', 'Vincent', 'Yannick',
      'Adrien', 'Bastien', 'Clement', 'Damien',
      'Alexandre', 'Benoit', 'Christophe', 'Didier', 'Emile', 'Fabrice',
      'Gaetan', 'Hubert', 'Ivan', 'Jerome', 'Laurent', 'Maxime',
      'Nicolas', 'Octave', 'Pascal', 'Raphael', 'Stephane', 'Theo',
      'Valentin', 'Xavier', 'Yann', 'Arnaud', 'Bertrand', 'Corentin',
      'Denis', 'Edouard', 'Franck', 'Gilles', 'Hervi', 'Ismael',
      'Joachim', 'Lucien', 'Marius', 'Nolan', 'Odilon', 'Patrice',
      'Romain', 'Sylvain', 'Tristan', 'Ugo', 'Victor', 'Aurelien',
      'Cyprien', 'Dorian',
    ],
    lastNames: [
      'Aubertin', 'Belmondier', 'Chevrolier', 'Dauphine', 'Estival', 'Fourcade',
      'Guerlain', 'Hachette', 'Ivernel', 'Joubert', 'Lacaze', 'Marchandeau',
      'Noirval', 'Ouvrard', 'Pellerin', 'Quesnel', 'Roussillon', 'Sarrazin',
      'Trouvelot', 'Vaugrenard', 'Wattelier', 'Boisseau', 'Charmoy', 'Delaunay',
      'Anquetil', 'Bellanger', 'Chevrolet', 'Escoffier', 'Fontenelle', 'Gaudreau',
      'Hautecoeur', 'Isambert', 'Jouvenel', 'Lachapelle', 'Marchand', 'Noirot',
      'Ollivier', 'Peyrefitte', 'Rocheteau', 'Sauvageot', 'Thevenin', 'Urbain',
      'Valcourt', 'Wavrin', 'Ybert', 'Cazenave', 'Duchemin', 'Espinasse',
      'Grandmaison', 'Hennequin', 'Jaubert', 'Lassalle', 'Monnereau', 'Nogaret',
      'Osselin', 'Pouliquen', 'Ramoneda', 'Sabourin', 'Tanguy', 'Vauquelin',
      'Amouroux', 'Barrault', 'Chastaing', 'Delcourt', 'Fauveau', 'Gimenez',
      'Huchet', 'Jomard', 'Lebreton', 'Maufroy', 'Nourrigat', 'Pellissier',
      'Reynaud', 'Soubeyran', 'Trintignant', 'Vaillancourt', 'Boulanger', 'Charbonneau',
      'Desmarais', 'Fournival', 'Guilbert', 'Lavigne', 'Mercier', 'Perrault',
      'Roussel',
      // Ein paar schrullige darunter - selten genug, dass sie auffallen.
      'Croquemitaine', 'Pamplemousse', 'Boulanger-Dupont', 'Chapeaurouge',
      'Trompette', 'Vinaigrier', 'Gribouille', 'Pomponnet',
      'Ratatouille', 'Soufflard', 'Ficelle', 'Cabriole',
    ],
    cities: [
      'Beaumont', 'Valcourt', 'Roquefer', 'Montclair', 'Saint-Aubin', 'Lisieres',
      'Chantonne', 'Fontenoy', 'Grandvaux', 'Hauteclair', 'Merigny', 'Pontarlie',
    ],
    clubPrefixes: ['AS', 'FC', 'Olympique', 'Racing', 'Stade', 'US'],
    clubSuffixes: ['', '', '', 'FC'],
    managerFirst: ['Gerard', 'Michel', 'Laurent', 'Pascal', 'Herve'],
  },
  batavia: {
    firstNames: [
      'Sven', 'Joris', 'Bram', 'Ruben', 'Thijs', 'Daan', 'Sem', 'Lars',
      'Jesper', 'Milan', 'Cas', 'Teun', 'Stijn', 'Niels', 'Koen', 'Wouter',
      'Bas', 'Jelle', 'Mees', 'Roel', 'Sander', 'Tijmen', 'Vincent', 'Wessel',
      'Aron', 'Boaz', 'Dirk', 'Elias', 'Ferdi', 'Gijs', 'Hidde', 'Ivar',
      'Jorrit', 'Kars', 'Levi', 'Maarten', 'Nout', 'Olivier', 'Pepijn', 'Quinten',
      'Rens', 'Siem', 'Tygo', 'Vince', 'Xander', 'Youri', 'Ziggy', 'Bjorn',
      'Chiel', 'Douwe', 'Evert', 'Freek', 'Guus', 'Huub',
    ],
    lastNames: [
      'van Bergen', 'de Waal', 'Vermeulen', 'Hoekstra', 'van Dijkhuizen',
      'Bakhuis', 'de Ruiter', 'Veenstra', 'van Oosten', 'Molenaar',
      'Kuipers', 'van Doorn', 'Brouwers', 'de Groot', 'Verhoeven',
      'Nieuwenhuis', 'van Leeuwen', 'Schouten', 'Timmermans', 'de Bruijn',
      'Wouters', 'van Rooij', 'Dekkers', 'Boersma', 'Hendriks',
      'van Kempen', 'Sluijter', 'Doornbos', 'van Aalst', 'Reijnders',
      'Blankestijn', 'Coppens', 'Damstra', 'Elzinga', 'Fokkema',
      'Grootveld', 'Haverkamp', 'IJsselstein', 'Jonker', 'Klinkhamer',
      'Lubbers', 'Meeuwsen', 'Nagelkerke', 'Oosterhuis', 'Pluimers',
      'Roeloffs', 'Steenbergen', 'Terlouw', 'Uilenberg', 'Vlietstra',
      'Wildeboer', 'Zeeman', 'Aardema', 'Beukema', 'Cnossen',
      'van der Sloot', 'Kruithof', 'Ravensbergen', 'Schuurmans', 'Vonk',
      'Peperkamp', 'Botterbloem', 'Kaasjager', 'Windvogel',
    ],
    cities: [
      'Vaarwijk', 'Nieuwhaven', 'Dijkstede', 'Molenbeek', 'Rietveld',
      'Zandvoorde', 'Waterlinde', 'Groenendal', 'Polderzicht', 'Havenstad',
      'Sluisdam', 'Eikenhorst', 'Meerdonk', 'Kanaalstede', 'Bosveld',
      'Duinberg', 'Vlietmond', 'Steenwijk',
    ],
    clubPrefixes: ['', '', '', 'FC', 'SC', 'VV'],
    clubSuffixes: ['', '', 'Boys', 'United', 'Ajaxis', 'Sport', 'Combinatie'],
    managerFirst: ['Rinus', 'Guus', 'Louis', 'Wim', 'Hennie', 'Foppe'],
  },
  lusitania: {
    firstNames: [
      'Rui', 'Tiago', 'Bruno', 'Nuno', 'Ricardo', 'Diogo', 'Goncalo', 'Vasco',
      'Duarte', 'Miguel', 'Andre', 'Fabio', 'Hugo', 'Ivo', 'Joao', 'Luis',
      'Mateus', 'Nelson', 'Otavio', 'Paulo', 'Rafael', 'Simao', 'Telmo', 'Vitor',
      'Afonso', 'Bernardo', 'Cristiano', 'Dinis', 'Edgar', 'Filipe', 'Gabriel', 'Henrique',
      'Isaac', 'Jorge', 'Leandro', 'Marco', 'Nicolau', 'Octavio', 'Pedro', 'Quim',
      'Renato', 'Salvador', 'Tomas', 'Ubaldo', 'Valentim', 'Xavier', 'Zeca', 'Anselmo',
      'Baltasar', 'Custodio', 'Dario', 'Elias',
    ],
    lastNames: [
      'Carvalhosa', 'Menezes', 'Vasconcelos', 'Albuquerque', 'Figueiredo',
      'Nogueira', 'Sampaio', 'Teixeira', 'Baptista', 'Cordeiro',
      'Esteves', 'Fontoura', 'Guerreiro', 'Loureiro', 'Magalhaes',
      'Nascimento', 'Oliveira Pires', 'Pinheiro', 'Queiroz', 'Rebelo',
      'Salgueiro', 'Trindade', 'Valadares', 'Xavier', 'Almeida Cruz',
      'Bettencourt', 'Coutinho', 'Damasceno', 'Espirito', 'Faria',
      'Gouveia', 'Henriques', 'Infante', 'Jesus Lima', 'Lobato',
      'Macedo', 'Neves', 'Osorio', 'Paredes', 'Quintela',
      'Ramalho', 'Seabra', 'Tavares', 'Vilanova', 'Zamith',
      'Bragancao', 'Carrico', 'Dourado', 'Estrela', 'Freitas',
      'Godinho', 'Hortelao', 'Lousada', 'Mesquita', 'Palminha',
      'Peixinho', 'Cebolinha', 'Chapeleiro', 'Rabanete',
    ],
    cities: [
      'Vila Serena', 'Porto Alvo', 'Ribeira Nova', 'Monteverde', 'Casteloso',
      'Praia Larga', 'Serra Doce', 'Fonte Clara', 'Alto Mirante', 'Vale Fundo',
      'Barra Azul', 'Pinhalvo', 'Estrelinha', 'Cabo Rijo', 'Douraval',
      'Aguadela', 'Torrejo', 'Salinhas',
    ],
    clubPrefixes: ['', '', 'SC', 'CD', 'GD', 'AD'],
    clubSuffixes: ['', '', '', 'Futebol Clube', 'Sporting', 'Uniao'],
    managerFirst: ['Fernando', 'Jorge', 'Artur', 'Manuel', 'Domingos', 'Anibal'],
  },
  amazonia: {
    firstNames: [
      'Caio', 'Vinicius', 'Lucas', 'Matheus', 'Gabriel', 'Rodrigo', 'Felipe', 'Thiago',
      'Bruno', 'Everton', 'Wesley', 'Douglas', 'Alisson', 'Danilo', 'Emerson', 'Fabricio',
      'Gilberto', 'Hernani', 'Igor', 'Juliano', 'Kleber', 'Leandro', 'Murilo', 'Nilton',
      'Otavio', 'Paulinho', 'Raoni', 'Samuel', 'Tarcisio', 'Ubirajara', 'Valdo', 'Washington',
      'Anderson', 'Breno', 'Cauan', 'Diego', 'Elton', 'Fernando', 'Guilherme', 'Heitor',
      'Ismael', 'Jandir', 'Kaique', 'Lorenzo', 'Maicon', 'Neymar', 'Oscar', 'Pablo',
      'Quesia', 'Ricardo',
    ],
    lastNames: [
      'Nascimento', 'Cavalcanti', 'Bittencourt', 'Guimaraes', 'Fonseca',
      'Andrade', 'Bezerra', 'Camargo', 'Dantas', 'Esteves',
      'Ferreira Lima', 'Goncalves', 'Herculano', 'Ipiranga', 'Juruna',
      'Klabin', 'Lacerda', 'Mendonca', 'Nunes Rocha', 'Odilon',
      'Paranhos', 'Quintanilha', 'Rezende', 'Siqueira', 'Tavares Melo',
      'Uchoa', 'Verissimo', 'Wanderley', 'Xavier Braga', 'Zabala',
      'Assuncao', 'Brandao', 'Cordeiro Reis', 'Delgado', 'Espindola',
      'Farias', 'Godoi', 'Hollanda', 'Ibrahim', 'Jacomo',
      'Krause', 'Lobato', 'Macieira', 'Nogueira Pires', 'Ostrowski',
      'Peçanha', 'Queiroga', 'Rondon', 'Sarmento', 'Trindade Alves',
      'Pipoca', 'Cascavel', 'Serelepe', 'Beija-Flor',
    ],
    cities: [
      'Rio Verde', 'Serra Azul', 'Porto Novo', 'Campo Belo', 'Vila Aurora',
      'Cachoeirinha', 'Morro Alto', 'Barra Funda', 'Itamaracu', 'Palmares',
      'Sao Jacinto', 'Boa Vista Nova', 'Araguaia', 'Tocantim', 'Guaruja',
      'Paranatinga', 'Jaguarina', 'Xingara',
    ],
    clubPrefixes: ['', '', 'EC', 'CR', 'AA', 'SE'],
    clubSuffixes: ['', '', 'Futebol', 'Atletico', 'Esporte', 'Nacional'],
    managerFirst: ['Zico', 'Telê', 'Vanderlei', 'Abel', 'Cuca', 'Odair'],
  },
  anatolia: {
    firstNames: [
      'Emre', 'Burak', 'Kerem', 'Ozan', 'Cengiz', 'Yusuf', 'Hakan', 'Serdar',
      'Arda', 'Berkay', 'Cihan', 'Deniz', 'Efe', 'Furkan', 'Gokhan', 'Halil',
      'Ilhan', 'Kaan', 'Levent', 'Mert', 'Nuri', 'Onur', 'Poyraz', 'Rasim',
      'Selim', 'Taner', 'Umut', 'Volkan', 'Yigit', 'Zeki', 'Ahmet', 'Baris',
      'Caner', 'Dogan', 'Ediz', 'Ferhat', 'Guven', 'Hasan', 'Ismet', 'Kadir',
      'Metin', 'Necati', 'Okan', 'Rifat', 'Sinan', 'Tolga', 'Ugur', 'Veli',
      'Yalcin', 'Zafer', 'Alper', 'Batuhan',
    ],
    lastNames: [
      'Yildirim', 'Kocaoglu', 'Demirtas', 'Ozturk', 'Aydemir',
      'Balaban', 'Cetinkaya', 'Doganay', 'Erdogmus', 'Findikli',
      'Gunduz', 'Hosgor', 'Isikli', 'Kayabasi', 'Levendoglu',
      'Mutlu', 'Nazlioglu', 'Ozdemir', 'Polatli', 'Sarikaya',
      'Tanriverdi', 'Uzuner', 'Varol', 'Yenilmez', 'Zorlu',
      'Akbulut', 'Bozkurt', 'Corlu', 'Dalkilic', 'Ekmekci',
      'Gultekin', 'Hamzaoglu', 'Ilgaz', 'Kurtulus', 'Merter',
      'Nalbant', 'Ortakoy', 'Pehlivan', 'Ruzgar', 'Sahinkaya',
      'Tekelioglu', 'Ulusoy', 'Vezirgil', 'Yavuzer', 'Ziyagil',
      'Basaran', 'Cakiroglu', 'Duygulu', 'Erenoglu', 'Gokdemir',
      'Bakliyat', 'Sekerci', 'Yorgancioglu', 'Tavukcu',
    ],
    cities: [
      'Akdeniz', 'Yesilova', 'Karatas', 'Gunesli', 'Denizkent',
      'Bogazici', 'Altinbas', 'Sariyaka', 'Tepekoy', 'Cinarli',
      'Beyazsu', 'Kizilkaya', 'Mavigol', 'Yenisehir', 'Dagkent',
      'Ovabasi', 'Kayalik', 'Pinarbasi',
    ],
    clubPrefixes: ['', '', '', 'SK'],
    clubSuffixes: ['spor', 'spor', 'spor', 'SK', 'Birlik', 'Genclik'],
    managerFirst: ['Fatih', 'Mustafa', 'Ersun', 'Aykut', 'Sergen', 'Tayfur'],
  },
};

export const STADIUM_WORDS = [
  'Arena', 'Stadion', 'Park', 'Sportpark', 'Kampfbahn', 'Waldstadion', 'Stadion am Ring',
];

/** Orte, nach denen traditionsreiche Stadien benannt sind ("Stadion an der ..."). */
export const STADIUM_PLACES = [
  'Bergstraße', 'Alten Försterei', 'Hafenmole', 'Mühlenaue', 'Kastanienallee',
  'Alten Ziegelei', 'Talbrücke', 'Weinsteige', 'Nordkurve', 'Schleuse',
];

/** Eigenstaendige Stadionnamen ohne Stadtbezug. */
export const STADIUM_STANDALONE = [
  'Waldstadion', 'Stadion am Hohen Wall', 'Grünwaldstadion', 'Sportpark Südhang',
  'Rheinauepark', 'Stadion Rote Erde', 'Weserkampfbahn', 'Stadion Alte Försterei',
];
